CREATE TABLE IF NOT EXISTS USUARIO(
    id_usuario INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    token VARCHAR(255),
    token_expires TIMESTAMP
); 
CREATE TABLE IF NOT EXISTS PRODUTO(
    id_produto INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    quantidade INT DEFAULT 0 NOT NULL
);
CREATE TABLE IF NOT EXISTS MOVIMENTACAO(
    id_movimentacao INT PRIMARY KEY AUTO_INCREMENT,
    id_produto INT NOT NULL,
    id_usuario INT NOT NULL,
    quantidade INT,
    tipo BOOLEAN,
    horario TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(id_produto) REFERENCES PRODUTO(id_produto) ON DELETE CASCADE,
    FOREIGN KEY(id_usuario) REFERENCES USUARIO(id_usuario)
);