CREATE TABLE USUARIO(
    id_usuario INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
) 
CREATE TABLE PRODUTO(
    id_produto INT PRIMARY KEY AUTO_INCREMENT,
    quantidade INT DEFAULT 0 NOT NULL
)
CREATE TABLE MOVIMENTACOES(
    id_movimentacao INT PRIMARY KEY AUTO_INCREMENT,
    id_produto INT,
    quantidade INT,
    tipo BOOLEAN,
    horario TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(id_produto) REFERENCES PRODUTO(id_produto)
)